title: Fist WebPage
author: nchantal101
email: cnyiramwiza@uh.com
description: > # this means to ignore newlines until "baseurl:"
  I can not wait to go through the progress, from start to finish.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  nchantal101 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
